In [15]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.regression.mixed_linear_model import MixedLM

In [4]:
combined_df = pd.read_excel('Combined_Dataframe_Corrected_Final.xlsx')
combined_df.head()

,Condition,Time,Dataset,Log_Time,Conjugation,R_a,Chemotaxis
0,Chemotaxis,19232,Chemotaxis_Diffusion,9.864331,True,True,True
1,Chemotaxis,11287,Chemotaxis_Diffusion,9.331407,True,True,True
2,Chemotaxis,21931,Chemotaxis_Diffusion,9.995656,True,True,True
3,Chemotaxis,19650,Chemotaxis_Diffusion,9.885833,True,True,True
4,Chemotaxis,26696,Chemotaxis_Diffusion,10.192269,True,True,True

### Conjugation R_a Regression Analysis

In [12]:
# Filter the dataframe to exclude the 'Chemotaxis_Diffusion' dataset
filtered_df = combined_df[combined_df['Dataset'] == 'Conjugation_Ra'].copy()

# Add interaction term for R_a * Conjugation
filtered_df['R_a_Conj'] = filtered_df['R_a'] & filtered_df['Conjugation']

# Display the first few rows to verify the new column
filtered_df[['Condition', 'Time', 'Dataset', 'Log_Time', 'Conjugation', 'R_a', 'R_a_Conj']].head()

,Condition,Time,Dataset,Log_Time,Conjugation,R_a,R_a_Conj
200,Normal Equation,1640,Conjugation_Ra,7.402452,True,True,True
201,Normal Equation,6705,Conjugation_Ra,8.810609,True,True,True
202,Normal Equation,4174,Conjugation_Ra,8.336630,True,True,True
203,Normal Equation,5143,Conjugation_Ra,8.545392,True,True,True
204,Normal Equation,6589,Conjugation_Ra,8.793157,True,True,True

In [29]:
# Prepare the model formula including the interaction term
formula = 'Log_Time ~ Conjugation + R_a'

# Fit the OLS regression model
model_interaction = sm.OLS.from_formula(formula, data=filtered_df).fit()

# Display the summary of the model
model_interaction_summary = model_interaction.summary()
print(model_interaction_summary)

                            OLS Regression Results
==============================================================================
Dep. Variable:               Log_Time   R-squared:                       0.019
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     3.873
Date:                Tue, 02 Jul 2024   Prob (F-statistic):             0.0216
Time:                        16:56:50   Log-Likelihood:                -311.03
No. Observations:                 400   AIC:                             628.1
Df Residuals:                     397   BIC:                             640.0
Df Model:                           2
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               8.7860      0.046    191.942      0.000       8.696       8.876
Conjugation[T.True]    -0.0435      0.053     -0.822      0.412      -0.147       0.060
R_a[T.True]            -0.1405      0.053     -2.659      0.008      -0.244      -0.037
==============================================================================
Omnibus:                        1.782   Durbin-Watson:                   2.045
Prob(Omnibus):                  0.410   Jarque-Bera (JB):                1.537
Skew:                          -0.126   Prob(JB):                        0.464
Kurtosis:                       3.170   Cond. No.                         3.19
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [27]:
# Prepare the model formula including the interaction term
formula = 'Log_Time ~ R_a_Conj'

# Fit the OLS regression model
model_interaction = sm.OLS.from_formula(formula, data=filtered_df).fit()

# Display the summary of the model
model_interaction_summary = model_interaction.summary()
print(model_interaction_summary)

                            OLS Regression Results
==============================================================================
Dep. Variable:               Log_Time   R-squared:                       0.018
Model:                            OLS   Adj. R-squared:                  0.015
Method:                 Least Squares   F-statistic:                     7.121
Date:                Tue, 02 Jul 2024   Prob (F-statistic):            0.00793
Time:                        16:54:01   Log-Likelihood:                -311.35
No. Observations:                 400   AIC:                             626.7
Df Residuals:                     398   BIC:                             634.7
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            8.7347      0.031    286.365      0.000       8.675       8.795
R_a_Conj[T.True]    -0.1628      0.061     -2.669      0.008      -0.283      -0.043
==============================================================================
Omnibus:                        2.039   Durbin-Watson:                   2.042
Prob(Omnibus):                  0.361   Jarque-Bera (JB):                1.806
Skew:                          -0.151   Prob(JB):                        0.405
Kurtosis:                       3.133   Cond. No.                         2.48
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Conclusion of Analysis and Comparison to Permutation Test:
- Conjugation is not a statistically significant predictor. (Coefficient is -0.0435, not significant p = 0.412).
- R_a is significant. (Coefficient is -0.1405, significant p = 0.008).
- R_a*Conj, Analysis with Interaction Term Only: (Coefficient is -0.1628, significant p = 0.008).
- Significant in the model focusing on interaction, indicating a combined effect that is crucial.
- The permutation test showed practical significance for the interaction effect but did not reach statistical significance.
- Regression results for R_a_Conj indicate a significant interaction effect in the model focusing on this term, aligning with the practical importance suggested by the permutation test.
- A higher R-squared indicates more variance in log('Time'), and higher F-statistic indicates that the model is more statistically significant, both indicate the model is a better fit.

### Chemotaxis Diffusion Regression Analysis

In [30]:
# Filter the dataframe to include only the 'Chemotaxis_Diffusion' dataset
chemotaxis_df = combined_df[combined_df['Dataset'] == 'Chemotaxis_Diffusion'].copy()

# Display the first few rows to verify
chemotaxis_df[['Condition', 'Time', 'Dataset', 'Log_Time', 'Chemotaxis']].head()

    Condition   Time               Dataset   Log_Time  Chemotaxis
0  Chemotaxis  19232  Chemotaxis_Diffusion   9.864331        True
1  Chemotaxis  11287  Chemotaxis_Diffusion   9.331407        True
2  Chemotaxis  21931  Chemotaxis_Diffusion   9.995656        True
3  Chemotaxis  19650  Chemotaxis_Diffusion   9.885833        True
4  Chemotaxis  26696  Chemotaxis_Diffusion  10.192269        True

In [33]:

# Prepare the model formula
formula = 'Log_Time ~ Chemotaxis'

# Fit the OLS regression model
model_chemotaxis = sm.OLS.from_formula(formula, data=chemotaxis_df).fit()

# Display the summary of the model
model_chemotaxis_summary = model_chemotaxis.summary()
print(model_chemotaxis_summary)

                            OLS Regression Results
==============================================================================
Dep. Variable:               Log_Time   R-squared:                       0.085
Model:                            OLS   Adj. R-squared:                  0.080
Method:                 Least Squares   F-statistic:                     18.29
Date:                Tue, 02 Jul 2024   Prob (F-statistic):           2.95e-05
Time:                        17:17:12   Log-Likelihood:                -10.991
No. Observations:                 200   AIC:                             25.98
Df Residuals:                     198   BIC:                             32.58
Df Model:                           1
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             10.1139      0.026    393.645      0.000      10.063      10.165
Chemotaxis[T.True]    -0.1554      0.036     -4.276      0.000      -0.227      -0.084
==============================================================================
Omnibus:                      109.938   Durbin-Watson:                   2.123
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              686.702
Skew:                          -2.056   Prob(JB):                    7.67e-150
Kurtosis:                      11.093   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.